--COMMON SCHEMA ACCESS
-- STG_DB
-- Create and Grant Privileges to Access Role __{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR (READ ONLY)

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR" REVOKE CURRENT GRANTS;

USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON DATABASE "{{ENV}}_{{TeamName}}_STG_DB" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT SELECT ON ALL TABLES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT SELECT ON FUTURE TABLES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT SELECT ON ALL VIEWS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT SELECT ON FUTURE VIEWS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON ALL STAGES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT READ ON ALL STAGES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON FUTURE STAGES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT READ ON FUTURE STAGES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT SELECT ON ALL STREAMS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT SELECT ON FUTURE STREAMS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON ALL PROCEDURES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR";


-- Create and Grant Privileges to Access Role __{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR (READ WRITE)
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON DATABASE "{{ENV}}_{{TeamName}}_STG_DB" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON ALL TABLES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON FUTURE TABLES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT SELECT ON ALL VIEWS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT SELECT ON FUTURE VIEWS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE,READ,WRITE ON ALL STAGES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE,READ,WRITE ON FUTURE STAGES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT SELECT ON ALL STREAMS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT SELECT ON FUTURE STREAMS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON ALL PROCEDURES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";
GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR";

-- Create and Grant Privileges to Access Role __{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT USAGE ON DATABASE "{{ENV}}_{{TeamName}}_STG_DB" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT USAGE ON SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL STAGES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA "{{ENV}}_{{TeamName}}_STG_DB"."COMMON" TO ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR";




-- Grant Access Roles to Functional Roles
USE ROLE SECURITYADMIN;
GRANT ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR" TO ROLE "{{ENV}}_{{Team}}_ADMIN_FR";
GRANT ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RO_AR" TO ROLE "{{ENV}}_{{Team}}_ANALYST_FR";
GRANT ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_FULL_AR" TO ROLE "{{ENV}}_{{Team}}_DATABRICKS_FR";
GRANT ROLE "__{{ENV}}_{{TeamName}}_STG_DB_COMMON_RW_AR" TO ROLE "{{ENV}}_{{Team}}_ENGINEER_FR";


USE ROLE SYSADMIN;