USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS {{ENV}}_SYSADMIN;
GRANT ROLE {{ENV}}_SYSADMIN TO ROLE SYSADMIN;
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE {{ENV}}_SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE {{ENV}}_SYSADMIN;

USE ROLE {{ENV}}_SYSADMIN;
CREATE DATABASE IF NOT EXISTS {{ENV}}_{{TeamName}}_{{ProjectName}}_DB;
USE ROLE SYSADMIN;


