name: Downstream Workflow
on: [repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering the Downstream Workflow"
      - name: Checkout
        uses: actions/checkout@v2
